version: "3"

services:

  mysql:
    image: mysql:8
    container_name: appointment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appointment_scheduler
    ports:
      - "3306:3306"

  backend:
    build: ./appointment-scheduler
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: appointment_scheduler
      DB_USER: root
      DB_PASSWORD: password
