services:

  backend:
    build: ./appointment-scheduler
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./appointment-scheduler-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
