services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointments
    ports:
      - "3306:3306"

  backend:
    build: ./appointment-scheduler
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./appointment-scheduler-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
